#!/bin/bash

######################################
#
#    What a wonderful morning...
#    ... Spunk!
#
######################################

# Use -m $msg to add all files and push commit to git.
#

# test dependencies
args=("$@")

function gitCommitAll {

	git add .
	git commit -m $1
	git push
}

# http://stackoverflow.com/a/24210877/288644
function get_branch {
      git branch --no-color | grep -E '^\*' | awk '{print $2}'
}

function gitPullAll {

	branch=`get_branch`
	git stash
	git checkout staging && git pull
	git checkout master && git pull
	git checkout ${branch} && git pull
}

function tmuxNode {
	tmux
	tmux split-window 'exec node'
	tmux select-pane -U
	git status
}

for key in ${!args[@]}; do

	param=${args[$key]}

	case "$param" in

		# git commit all
		-m)
			msg=${args[$key+1]}
			gitCommitAll $msg
		;;

		# git pull (staging & master)
		pulled-onions)
			gitPullAll
		;;

		fart-bubble)
			tmuxNode
		;;

		# autocomplete
		shortlist)
			pulled-onions
		;;

	esac
done
